/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedHospitalCenterRouteImport } from './routes/_authenticated/hospital-center'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated/sos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHospitalCenterRoute =
  AuthenticatedHospitalCenterRouteImport.update({
    id: '/hospital-center',
    path: '/hospital-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/hospital-center': typeof AuthenticatedHospitalCenterRoute
  '/live': typeof AuthenticatedLiveRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/sos': typeof AuthenticatedSosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/hospital-center': typeof AuthenticatedHospitalCenterRoute
  '/live': typeof AuthenticatedLiveRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/sos': typeof AuthenticatedSosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doctor': typeof AuthenticatedDoctorRoute
  '/_authenticated/hospital-center': typeof AuthenticatedHospitalCenterRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/doctor'
    | '/hospital-center'
    | '/live'
    | '/requests'
    | '/sos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/doctor'
    | '/hospital-center'
    | '/live'
    | '/requests'
    | '/sos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/doctor'
    | '/_authenticated/hospital-center'
    | '/_authenticated/live'
    | '/_authenticated/requests'
    | '/_authenticated/sos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospital-center': {
      id: '/_authenticated/hospital-center'
      path: '/hospital-center'
      fullPath: '/hospital-center'
      preLoaderRoute: typeof AuthenticatedHospitalCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRoute
  AuthenticatedHospitalCenterRoute: typeof AuthenticatedHospitalCenterRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRoute,
  AuthenticatedHospitalCenterRoute: AuthenticatedHospitalCenterRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
